# action.yml
name: 'Convert Veracode Pipeline to SARIF'
description: 'Convert the output results file from Veracode Pipeline Scan to a valid SARIF file'
inputs:
  pipeline-results-json:  # id of input
    description: 'location of the pipeline json result file'
    required: true
    default: 'results.json'
  output-results-sarif:  # id of input
    description: 'the path to the SARIF file as an output of the transformation'
    required: true
    default: 'veracode-results.sarif'
runs:
  using: 'node12'
  main: 'convert-action.js'
